ColorFilter:
  color_list: [[225, 225, 225], [112, 206, 244]]
  color_label: ['white', 'yellow']
  color_threshold: 120
  area_threshold: 20
  save_flag: true

Predictor:
  checkpoint: './checkpoints/sam_vit_h_4b8939.pth'
  usage_list: ['default', 'square', 'yellow', 'arrow', 'line']
  max_area_threshold: [30000, 750000, 750000, 40000, 30000]
  min_area_threshold: [100, 100, 100, 10000, 100]
  color_threshold: 120
  pixel_cm: 1
  save_flag: true